### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by omkar-pednekar** [fiasco/async#2]
```
Executing: ./vendor/bin/drutiny profile:run acn_readiness_audit -f csv -o reports/polaris aht:@aaanational.prod -vvv

Fatal error: Uncaught TypeError: Argument 1 passed to Seld\Signal\SignalHandler::create() must be of the type array or null, string given, called in /drutiny-cs-adaptor/vendor/fiasco/async/src/Signal.php on line 23 and defined in /drutiny-cs-adaptor/vendor/seld/signal-handler/src/SignalHandler.php:247
Stack trace:
#0 /drutiny-cs-adaptor/vendor/fiasco/async/src/Signal.php(23): Seld\Signal\SignalHandler::create('SIGINT', Object(Closure))
#1 /drutiny-cs-adaptor/vendor/fiasco/async/src/Channel.php(18): Async\Signal::register(Array, Object(Closure))
#2 /drutiny-cs-adaptor/vendor/fiasco/async/src/ForkManager.php(50): Async\Channel->__construct()
#3 [internal function]: Async\ForkManager->__construct(Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(Monolog\Logger))
#4 /drutiny-cs-adaptor/vendor/symfony/dependency-injection/ContainerBuilder.php(1105): ReflectionClass->newInstanceArgs(Array)
#5 /drutiny-cs-adaptor/vendor/symfony/dependency-injection/ContainerBuilder.php(608): Symfony\Component\DependencyInjection\ in /drutiny-cs-adaptor/vendor/seld/signal-handler/src/SignalHandler.php on line 247
```

**Comment by omkar-pednekar** [comment]
@fiasco ,

Looks like this issue is fixed in master branch.
Fix: https://github.com/fiasco/async/commit/8ffb3e7635174e7c6110c5a7fc71fc7847d56beb

Drutiny is picking latest beta release which is `1.0-beta4` and fix is not in this release.
```
# omkar @ MacBookPro-OmkarPednekar in ~/Projects/drutiny-cs-adaptor on git:4.x x [16:44:29] 
$ composer show fiasco/async
name     : fiasco/async
descrip. : PHP library for running asynchronous runtime php forks using pcntl.
keywords : 
versions : * 1.0-beta4
type     : library
license  : GNU General Public License v3.0 or later (GPL-3.0-or-later) (OSI approved) https://spdx.org/licenses/GPL-3.0-or-later.html#licenseText
homepage : 
source   : [git] https://github.com/fiasco/async.git bc99910fca8e1222f0b0db10b9306877938ea189
dist     : [zip] https://api.github.com/repos/fiasco/async/zipball/bc99910fca8e1222f0b0db10b9306877938ea189 bc99910fca8e1222f0b0db10b9306877938ea189
path     : /Users/omkar/Projects/drutiny-cs-adaptor/vendor/fiasco/async
names    : fiasco/async

support
issues : https://github.com/fiasco/async/issues
source : https://github.com/fiasco/async/tree/1.0-beta4

autoload
psr-4
Async\ => src/

requires
psr/log ~1.0
seld/signal-handler ^1.2
symfony/event-dispatcher ^5.0

requires (dev)
phpunit/phpunit ^9
symfony/console ^5.1
```
I think we need to create a new beta tag so that Drutiny can pick it up or we need to change in drutiny's composer to pick master branch. What do you think?

**Comment by omkar-pednekar** [comment]
Closing this issue as new tag is available with this fix.
